### ISSUE TITLE
Search for person by name

### ISSUE THREAD

**Issue by quicquid** [Forum-Informationsfreiheit/OffenesParlament#105]
I'd like to search for a person by name only (e.g. Karl Gruber is interesting because there were two of them active). I can select as sole criterion "Person" and hit the search button, but this gives more than 2000 results on 6 pages. How do I restrict a person search to a specific name?

**Comment by fin** [comment]
You can select the Search Type (Suchtyp) of Person and remove the Legislative Period (Gesetzgebungsperiode) filter, arriving at this:
http://offenesparlament.at/suche/personen?q=Karl+Gruber

**Comment by quicquid** [comment]
I see you need to click inside the box labeled "text". I tried clicking outside which adds another restriction.
