### ISSUE TITLE
[CodeBounty] Verbindung mit Lobbyregister

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#11]
# Verbindung mit Lobbyregister

**Scraper**: € 200
**Frontend**: € 200

Lobbyregister Scrapen und bei Stellungnahmen zu Gesetzesvorschlägen und bei BürgerInneninitiativen prüfen (fuzzy matching), ob sie von im Lobbyregister eingetragenen Organisationen stammen

http://www.lobbyreg.justiz.gv.at/

**Comment by fin** [comment]
(1) Die Bundesministerin für Justiz führt automationsunterstützt ein Lobbying- und
Interessenvertretungs-Register, in das
1. Lobbying-Unternehmen (Abteilung A1) sowie deren Aufgabenbereiche (Abteilung A2),
2. Unternehmen, die Unternehmenslobbyisten beschäftigen (Abteilung B), sowie
3. Selbstverwaltungskörper (Abteilung C) und
4. Interessenverbände (Abteilung D)

aus: https://www.ris.bka.gv.at/Dokumente/BgblAuth/BGBLA_2012_I_64/BGBLA_2012_I_64.pdf

**Comment by fin** [comment]
Geschlossen weil implementiert.
