### ISSUE TITLE
[CodeBounty] Visualisierung des Gesetzgebungsprozesses

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#12]
# Visualisierung des Gesetzgebungsprozesses

**Frontend**: € 500

Der Gesetzgebungsprozess ist nicht ohne Tücken. Wie weit ein Gesetz in diesem Prozess ist, und was es noch vor sich hat, wollen wir sinnvoll darstellen können.

_Challenges_: 
- Wie auf Mobil? 
- Womöglich mehrere Varianten, je nach Platzangebot

Die Abnahme dieser Code Bounty erfolgt sehr subjektiv - Wir geben gerne Feedback zu Design-Ideen!

**Comment by fin** [comment]
Geschlossen weil Code Bounties leider nicht mehr aktuell sind. Wir freuen uns trotzdem über Hilfe!
