### ISSUE TITLE
Inconsistency in Parlamentarische Anfrage?

### ISSUE THREAD

**Issue by quicquid** [Forum-Informationsfreiheit/OffenesParlament#120]
Please have a look at http://offenesparlament.at/gesetze/XXIV/J_14787/ - the history at the bottom provides the answer (Anfragebeantwortung), but the label on top reads: "Noch nicht beantwortet von Mag. Dr. Beatrix Karl". It should refer to the answer instead.

**Comment by fin** [comment]
thanks for reporting, a re-run of the scrapers over next weekend should fix any remaining instances of this issue!
