### ISSUE TITLE
Werden CodeBountys noch vergeben/ausgezahlt? 

### ISSUE THREAD

**Issue by PeterTheOne** [Forum-Informationsfreiheit/OffenesParlament#121]
> Wie auf unseren Hackdays mehrfach erwähnt, läuft unser Projekt nur mehr bis Ende März; wir haben uns daher dafür entschieden, Code-Bounties nur mehr bis Mitte März abschliessen zu lassen (was danach kommt, könnten wir auch nicht mehr rechtzeitig prüfen und einfügen).

– https://github.com/Forum-Informationsfreiheit/OffenesParlament/issues/10#issuecomment-190143627

Wenn nein, dann bitte bei den entsprechenden Issues dazuschreiben, danke. :)

**Comment by fin** [comment]
Danke! Wir können leider wegen Förderungsende keine CodeBounties mehr auszahlen, habe ich in den relevanten Issues jetzt klargestellt (:
