### ISSUE TITLE
Search not restricted to selected Peroid

### ISSUE THREAD

**Issue by quicquid** [Forum-Informationsfreiheit/OffenesParlament#126]
I tried to find the protocol of the youtube Video https://www.youtube.com/watch?v=GN3lXl57Mtg . For this I selected the period from 2009, debates in the Nationalrat and looked for the text "Adler" which is part of the speech.

The Link http://www.offenesparlament.at/suche/debatten?llps=XXIV&debate_type=NR&q=Adler apparently contains this information, but nevertheless I receive results from 2016 (see picture attached). Am I doing something wrong?

![screenshot-op](https://cloud.githubusercontent.com/assets/436903/16736914/65e909e8-478f-11e6-9b51-afe16aeb139d.png)

**Comment by fin** [comment]
hey,

thanks for your report. checking and debugging this is definitely on my todo. sorry for the long response time. i really want to find out what's going wrong here.

best
-f

**Comment by quicquid** [comment]
Don't worry, please let me know if i can be of any assistance.

cheers, m

**Comment by benfreu** [comment]
The issue probably was the wrong date for debates. All the debates in the search result actually are from the correct period. Should be fixed by 703e38eafe39b4247472873b33dbe8c9b08d66bd
