### ISSUE TITLE
[CodeBounty] Free-Form

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#13]
# Free-Form:

Datendarstellung bzw -zusammenführung

**Frontend**: € 400

Eine Free-Form Code Bounty!
Hast Du spannende Ideen für Datenvisualisierungen, die man in OffenesParlament.at integrieren könnte?
Kann man verschiedene Bereiche von Parlamentsaktivitäten zusammenführen, die noch nicht miteinander verknüpft sind?

Hier kannst Du’s versuchen!

Die Abnahme dieser Code Bounty erfolgt sehr subjektiv - Wir geben gerne Feedback zu Design-Ideen!

**Comment by hias234** [comment]
Im Zuge meiner Bachelorarbeit (noch nicht ganz fertig) habe ich in einem Java-Programm Daten aus den stenographischen Protokollen (https://www.parlament.gv.at/PAKT/STPROT/) extrahiert und in eine Postgresql-DB gespeichert. Ich habe die Sitzungen, Diskussionen und Diskussionsansprachen, sowie die Politikern mit Klubzugehörigkeit herausgeholt und die Daten via WebApp visualisiert.

Da die Mehrheit der Ansprachen der Politiker mit "pro" oder "contra" getaggt ist, habe ich darauf aufbauend Graphen erstellt, die durch physische Nähe zeigen, welche Parteien tendenziell gleichgesinnt sind. Dadurch sieht man dann auf einen Blick, wie die einzelnen Parteien in Relation stehen. 

Github-Repository findet sich hier: https://github.com/hias234/AustrianParliamentAnalyzer
Meine Bakk-Arbeit (falls für irgendwen interessant): https://github.com/hias234/AustrianParliamentAnalyzerBachelorThesis

Hier ein Beispiel für einen Relationsgraph der Politiker (25. GGP):
![period25_mincount2](https://cloud.githubusercontent.com/assets/2743335/11660396/4142b0ce-9dcd-11e5-9054-da6e7762e24f.PNG)

Ein Partei-Graph (auch 25. GGP):
![image](https://cloud.githubusercontent.com/assets/2743335/11660449/6f6a3f1c-9dcd-11e5-9935-d1cfecd53e76.png)

Weiters kann man damit berechnen in welchem Grad sich die Meinungen der Politiker in Regierung und Opposition unterscheiden und in welcher Beziehung ein Politiker zu einer Partei steht.

Die Webanwendung ist noch nicht online, obwohl schon mehr oder weniger fertig.

Solche Graphen könnten evtl. auch für eure website interessant sein, oder?

**Comment by fin** [comment]
Markus,

das sieht großartig aus!
Besonders spannend für uns wäre, wenn solche Graphen jederzeit basierend auf dem Datenbestand, der in unserer Datenbank vorliegt erstellbar wären.
Hättest du Interesse, die Graphen daran anzupassen - und in unsere Seite einbettbar zu machen?

Würde mich freuen, wenn wir so unsere erste Free Form Code Bounty vergeben könnten (:
Der Reden-Scraper wird auch langsam, höre ich (:

PS: cooles Bachelorarbeit-Thema, finde ich!

**Comment by hias234** [comment]
Die Graphen werden in meiner Applikation bereits aus den aktuellen Datenbestand erstellt. Ich könnte die Graphen aus eurer DB erstellen, sobald der Reden-Scraper fertig ist -> daraus muss ich dann die Gewichte der Politiker/Klubs errechnen.

**Comment by benfreu** [comment]
Nachdem Abgeordnete bei dir eh mehrdimensionale Vektoren sind... Hast Du dir schon einmal t-SNE https://lvdmaaten.github.io/tsne/ angeschaut? Das könnte unabhängig (aber auch im Kontext) von OffenesParlament spannend für dich sein.

**Comment by hutershvili** [comment]
Hi Markus, 
wir machen noch einen OffenesParlament-Hackday, am Dienstag, 2. Februar 2016, ab 18:00
im Metalab, Rathausstraße 6, 1010 Wien. Vielleicht hast du Zeit und Lust, vorbeizukommen? Wir suchen insbesondere noch Leute, die an Front-End und Visualisierung von gescrapten Daten mitarbeiten möchten. Einladung: http://www.informationsfreiheit.at/2016/01/22/einladung-zum-offenesparlament-hackday-4-am-2-februar-2016/

**Comment by hias234** [comment]
hi,

sorry, dass ich erst jetzt zurückschreibe, aber ich schaffe es nicht zu eurem Hackday. Habe heute noch eine Klausur gehabt.
Bzgl. der Entwicklung des Graphen: Ich habe mir mal euer Datenmodell angesehen und da fehlt leider ein essentieller Bestandteil für mein Berechnungsverfahren. In meiner Bakk-Arbeit habe ich die Reden während einer Sitzung auch in Diskussionen aufgeteilt und auch herausgeholt ob sie pro bzw contra waren (das ist ebenfalls bei den Protokollen vermerkt). Ohne diese Daten kann ich den Graphen nicht aufbauen... Mal schauen ob das noch irgendwie zu integrieren ist.

mfg Markus

**Comment by benfreu** [comment]
Hi Markus,

das müsste das sein, was bei uns im Frontend "Redebeiträge" und im model 
Statement mit dem Attribut "speech_type" heißt. ZB hier 
http://staging.offenesparlament.at/personen/PAD_08242/Kogler-Werner-Mag-/
Hilft dir das?

Liebe Grüße
Ben

**Comment by fin** [comment]
Geschlossen weil Code Bounties leider nicht mehr aktuell sind. Wir freuen uns trotzdem über Hilfe!

@hias234 wenn du immer noch interessiert bist, deine Visualisierung zu integrieren, sag Bescheid (:
