### ISSUE TITLE
Speeches of MPs are not updated

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#142]
It appears that speeches of MPs are not updated on their profiles. Example: the last speech given by Kickl listed is from 2015, https://offenesparlament.at/personen/PAD_35520/Kickl-Herbert/. They should also link to the speech, not only to the law that was discussed. 

The official page lists many recent speeches he gave: https://www.parlament.gv.at/WWER/PAD_35520/index.shtml#tab-Plenum

**Comment by fin** [comment]
is this the same issue as #128?

**Comment by hutershvili** [comment]
duplicate of #128
