### ISSUE TITLE
MPs: "Politische Mandate" are listed twice

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#150]
The political mandates (politische Mandate) of MPs are listed twice in slightly different ways on the site of each MP.

Example, https://offenesparlament.at/personen/PAD_01210/Pilz-Peter-Dr-/
![image](https://user-images.githubusercontent.com/2070925/32543009-b4f2d29a-c474-11e7-88e5-5e00566b7983.png)

**Comment by fin** [comment]
should be fixed by 472c12b, will deploy it over the weekend

**Comment by hutershvili** [comment]
The issue appears to be fixed for Nationalratsabgeordnete, but for Bundesratsabgeordnete, their Mandates are listed multiple times (10x). 

Example: https://offenesparlament.at/personen/PAD_88956/Seeber-Robert/

![image](https://user-images.githubusercontent.com/2070925/32981723-a93258c4-cc79-11e7-83fa-20f5a8f6e827.png)
