### ISSUE TITLE
Beim scrapen der Bildadressen dürfte sich ein Bug eingeschlichen haben

### ISSUE THREAD

**Issue by nabittened** [Forum-Informationsfreiheit/OffenesParlament#156]
Anscheinend zeigen immer mehr Bildlinks auf https://www.parlament.gv.at/.

z.B  bei Stephanie Cox war der Link bis vor kurzem noch https://www.parlament.gv.at/WWER/PAD_02340/7184373_384.jpg. Auf parlament.gv.at scheint sich aber nix geändert zu haben

**Comment by lyrixderaven** [comment]
Ist kein Bug, aber der Template-Code auf der Parlamentsseite hat sich geändert. Früher war das Bild  unter dem XPATH 

`"//div[contains(concat(' ', normalize-space(@class), ' '), ' teaserPortraitLarge ')]/a/img/@src"`

zu finden, jetzt sind da 3 neue divs dazu gekommen:

```
<div class="bildContainer teaserPortraitLarge copyright" style="float: Right">
  <div class="image-container">
    <figure class="image">
      <div class="image__container">
        <picture>
          <!--[if IE 9]><video style="display: none;"><![endif]-->
          <source srcset="/WWER/PAD_02340/7184373_180.jpg" media="(min-width: 1024px)">
          <source srcset="/WWER/PAD_02340/7184373_180.jpg" media="(min-width: 768px)">
          <source srcset="/WWER/PAD_02340/7184373_500.jpg" media="(min-width: 481px)">
          <!--[if IE 9]></video><![endif]-->
         <img alt="Abgeordnetenportrait der XXVI. Gesetzgebungsperiode" src="/WWER/PAD_02340/7184373_500.jpg">
       </picture>
     </div>
   </figure>
  <a class="zeigeTooltip" href="/WWER/PAD_02340/7184373_500.shtml" onclick="javascript:self.location.href='/WWER/PAD_02340/7184373_500.shtml?backurl='+ encodeURIComponent(location.href.replace(/\&amp;/g, '&amp;'));return false;" target="_blank" title="Dieser Link öffnet die Bildvorschau (in einem externen Fenster, wenn Javascript nicht aktiviert ist).">
<span title="©&nbsp;Parlamentsdirektion / PHOTO SIMONIS" class="zeigeTooltip tooltip-lightbox">©</span></a>
</div>
</div>
```

Hier wird es eine Anpassung des Scrapers brauchen, konkret im File [`offenesparlament/op_scraper/scraper/parlament/resources/extractors/person.py:28`](https://github.com/Forum-Informationsfreiheit/OffenesParlament/blob/7c91ff10826e6b4a5772059794e1298b1e4779ce/offenesparlament/op_scraper/scraper/parlament/resources/extractors/person.py#L28)
