### ISSUE TITLE
Use Django-Configuration to create&maintain different test/deploy configs

### ISSUE THREAD

**Issue by fin** [Forum-Informationsfreiheit/OffenesParlament#3]
This should enable us to create test/dev/deploy configs without having to maintain a completely-seperate local_settings out of repo

further reading:
- https://django-configurations.readthedocs.org/en/latest/
- https://froide.readthedocs.org/en/latest/herokudeployment/?highlight=django_configuration

examples:
- https://github.com/fin/fragdenstaat.at/blob/master/froide_theme/settings.py
- https://github.com/fin/fragdenstaat.at/blob/master/froide_theme/local_settings.py.example

thoughts?

**Comment by lyrixderaven** [comment]
Seeing as we're nearing an end of the django-configuraions/celery issues, I'd say we can close this issue. The decision has been made to go with it, I guess?

**Comment by fin** [comment]
code says yes, let's close it. fixed by 16d0f9d7fdf2e77f49dce9b6d34cadaf0f13249a and earlier
