### ISSUE TITLE
vagrant/instruction issues

### ISSUE THREAD

**Issue by fin** [Forum-Informationsfreiheit/OffenesParlament#4]
point 8 on the vagrant setup instructions is to run grunt in /vagrant, however
(1) it complains that grunt-contrib-watch is not installed
(2) after npm install, it complains that ruby and sass are needed for things to work:

Warning:
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Used --force, continuing.
Warning: spawn ENOENT Used --force, continuing.
Warning: spawn ENOENT Used --force, continuing.

could you shed a light on this?

**Comment by benfreu** [comment]
fixed by commit 403c549373f0ec6e091185561cbb23f4d89fdee1

in your existing vagrant VM run `sudo gem install sass`
