### ISSUE TITLE
Search View doesn't change the URL when on Detail page

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#42]
When I'm on a detail page (for instance, [this](http://offenesparlament.vm:8000/personen/PAD_02708/Harald-Vilimsky/) one) and change/edit the search bar in any way, i get the search results again (so far i think it's a wanted behaviour). But then these things happen: 
- the URL in the address bar doesn't change
  - a refresh of the page reloads the detail page, not the search page
  - subscribing the content will possibly subscribe the detail page, not the search page (please confirm this, i'm just guessing here)
- the title of the page is still the one of the detail page

This shouldn't happen, I think.

**Comment by benfreu** [comment]
Re subscribing content: Subscribing (the heart icon) via the search bar will always subscribe the query inside the search bar at that time. Not the URL in your browser.

**Comment by benfreu** [comment]
Resolved by 7483bc51037e0969d31110be91336d1db7545ab5
