### ISSUE TITLE
ES search returns 0 results for categories containing ":" or "/"

### ISSUE THREAD

**Issue by benfreu** [Forum-Informationsfreiheit/OffenesParlament#48]
Steps to reproduce:
Search for current LLP, Suchtyp: Gesetze, Kategorie: "Regierungsvorlage: Bundes(verfassungs)gesetz"

The server seems to understand the query correctly, as it logs this to the console:

```
INFO:offenesparlament.views.search:Searching <class 'op_scraper.models.Law'> with arguments [{'limit': 50, 'facet_filters': {'category': u'Regierungsvorlage: Bundes(verfassungs)gesetz', 'llps': u'XXV'}, 'offset': 0}]
```

The same happens for "Vorl. ü. Initiative/Beschluss des Europ. Rates und des Rates" and "Regierungsvorlage: Staatsvertrag"

**Comment by lyrixderaven** [comment]
Fixed in 907c17ce1a7dc03d677f5c3fafffb2d0d9d4d6cd
