### ISSUE TITLE
Subscriptions: Single/Detail Page subscription URL isn't working properly

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#50]
Subscribing a detail page (like the Person detail page for [Rosa Ecker](http://offenesparlament.vm:8000/personen/PAD_87002/Rosa-Ecker/)  doesn't provide a proper, single request link base on the parl_id (or parl_id and llp for laws), but instead uses the generic 'personen' search, which results in this link: 

http://offenesparlament.vm:8000/personen/search?llps=XXV&type=Personen&limit=-1&fieldset=all 

That of course isn't correct and yields problems when trying to subscribe and or collect the changes.

**Comment by lyrixderaven** [comment]
Correction: I clicked the 'subscribe' button in the search bar on the detail page instead of the button further down. Maybe we should hide the subscribe button in the search bar when you're on a detail page? It's confusing that you can subscribe a search while being on a detail page...

It's still not working correctly, though - the URL i'm given for Rosa Ecker is:

http://offenesparlament.vm:8000/suche/gesetze?parl_id=PAD_87002

which obviously can't be right (should be [...]/suche/personen?parl_idPAD_87002

**Comment by benfreu** [comment]
Which is the correct URL for detail searches? I thought it worked through the generic search with searching for a PARL_ID.

**Comment by benfreu** [comment]
@lyrixderaven is this now covered by the `category` POST parameter for the /subscribe endpoint?

**Comment by lyrixderaven** [comment]
The subscription URL _must_ point to the actual search view that returns JSON, not the public frontend view. A subscription process includes requesting the JSON data that the frontend normally requests via AJAX request and then indexing/hashing that. The error we are getting now has nothing to do with the fact that we are requesting a single person instead of a list, but with the fact that the '/suche/personen?[...]' url returns rendered frontend views instead of JSON. 

Since i've seen in your commit where you're setting this URL though, I'll try and correct it myself now.
