### ISSUE TITLE
[CodeBounty] Parlamentarische Anfragen & Beantwortungen

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#6]
# Parl. Anfragen & Beantwortungen

**Scraper**: € 600
**Frontend**: € 400
### Scraper

_Einstiegsseite_: http://www.parlament.gv.at/PAKT/JMAB/
_Detailseite (Beispiel)_: http://www.parlament.gv.at/PAKT/VHG/XXV/J/J_06430/index.shtml
_Detailseite (Beispiel, beantwortet)_: http://www.parlament.gv.at/PAKT/VHG/XXV/J/J_05835/index.shtml
_Detailseite 2 (Beantwortung)_: http://www.parlament.gv.at/PAKT/VHG/XXV/AB/AB_05632/index.shtml

_Zu Beachten_: 
- Anfragen können sowohl vom Bundesrat als auch vom Nationalrat gestellt werden - bitte beides beachten.
- Bitte immer die “Steps” - Historie der Anfrage inklusive Timestamps - parsen.
- ACHTUNG: Es könnte auch mündliche Beantwortungen geben

_Tips_: 
- Tabs auf den Detailseiten sind rein im Frontend implementiert; für das Scrapen daher am Besten immer die HTML-Source betrachten!
- Der RSS-Link auf der Einstiegsseite rechts oben bezieht sich immer auf die aktuell gewählten Formulareinstellungen - praktisch zum reverse engineering der URLs.
### Frontend

_Challenge_:
- gleichzeitige Darstellung von Anfragen und Antworten mittels pdf.js oder iframes, wenn HTML-Versionen vorhanden sind.
# Add-On: Inhalte aus PDFs & rudimentäre Fragen-Zuordnung

**Scraper**: € 1.800 (€ 600 ohne OCR, € 1800 mit OCR)
**Frontend**: € 600
### Scraper
- pdf2text oÄ die PDFs
- Zuordnung von Antworten zu Fragen (zB “Zu 1, 2, 3-9” den Fragen zuordnen)
- _Für Bonus-€_: OCR über die PDFs, um die Antworten durchsuchbar zu machen und die Antworten auch in gescannten Dokumenten den Fragen rudimentär zuordnen zu können
### Frontend
- Darstellung von Fragen und Antworten - auch Mobil - in einem Format, in dem sie zueinander zuordenbar sind. 
- Reihenfolge umschaltbar: Reihenfolge der Fragen, Reihenfolge der Antworten.

**Comment by shellmayr** [comment]
FYI, bin gerade dabei den ersten Scraper für die Anfrangen & Beantwortungen zu schreiben, fork ist in meinem Profil zu finden.

**Comment by hutershvili** [comment]
super!

**Comment by shellmayr** [comment]
Kleines Update über den Progress:
- schriftliche und mündliche Anfragen werden alle gescraped, Ausnahme ist wo eine Person referenziert wird die nicht existiert, aber da gibt es bisher nur einen Fall (Franz Fiedler)
- Dringliche Anfragen haben eine völlig andere Struktur, aber ähnelt den Laws&Initiatives, werden derzeit noch übersprungen aber ich bin gerade dabei das umzusetzen
- Beantwortungen sind noch nicht gemacht, Extractor und Model sind schon da, fehlt nur noch der Crawler an sich.

**Comment by lyrixderaven** [comment]
Nice, Code sieht auch gut aus (volles review mach' ich aber eh erst beim pull request später, damit ich das nicht doppelt machen muss :-))

Ad progress:
- Nicht-Existierende Personen können natürlich vorkommen, sind aber kein Drama - wir werden uns sicher am Schluss der Bounty noch gemeinsam anschauen, warum die Personen, die fehlen, nicht gescraped werden
- Dringliche Anfragen: wenn es mehr Sinn macht, das Law model anzupassen, um die Dringlichen Anfragen auch abzudecken, anstatt ein eigenes Model zu machen, ist das natürlich die bessere Option, aber wenn's zu kompliziert wird, tut's ein eigenes Model selbstverständlich auch.

Nicht vergessen, es wäre toll, wenn Du am Ende auch noch kurz in der Doku festhalten könntest, was der Scraper macht bzw. was Dir beim Coden sonst noch so aufgefallen ist (Spezialfälle, caveats, andere Problemchen), damit wir auch für die Zukunft daraus lernen können! Wenn Du da noch Hilfe brauchen solltest, helf' ich natürlich gern!

Ansonsten - danke für das Update!

**Comment by shellmayr** [comment]
Scraper ist von meiner Seite fertig: 
- die Exceptions die an dem ein oder anderen Punkt vorgekommen sind hab ich aufgefangen und wie besprochen durch Info-logs ersetzt
- Beantwortungen sind als ForeignKey in den Anfragen selbst umgesetzt, da eine Beantwortung auf mehrere Anfragen kommen kann, hat sich dann eh relativ schnell lösen lassen

@lyrixderaven schaust du noch mal rein ob alles für dich passt oder ob es noch was zu ändern/schreiben gibt bevor ich einen Pull Request stell, oder machst du das nachher?

**Comment by lyrixderaven** [comment]
Mach ich in einem Aufwaschen mit dem Pull-Request (vermutlich am Donnerstag werd' ich dazu kommen). Sollten sich dann noch Probleme ergeben, meld' ich mich eh' noch, keine Sorge :-) Danke erstmal!

**Comment by laszlokiraly** [comment]
Ich mach das Frontend dazu.

Im ersten Schritt mache ich folgendes:
- Auf Personendetail fuege ich eine Tabelle fuer alle Anfragen der Person hinzu
- Von der Zeile einer Anfrage kommt man auf die Anfragedetailseite, wo die Anfrage und, falls vorhanden, die Antwort dargestellt wird

Dann kann man sich anschauen was man verbessern und/oder erweitern kann:
- Mehrere Anfragen in Bloecke zusammenfassen, eventuell schon in der Tabellenansicht der Person
- Anfragedetail Seite fuer einen einzelnen Anfrageblock
- Navigieren zu oder darstellen aller Anfragen die mit einer Antwort bedient wurden
- Alarm wenn Anfrage beantwortet wurde
- Antworten mit Personen der Exekutive verlinken
- Layout
- ....

**Comment by shellmayr** [comment]
Wie sollen wir denn die Documentation der einzelnen Scraper am besten einbauen? Also als Unterkategorie von Scraping, eigenes .rst oder irgendwie anders?

**Comment by lyrixderaven** [comment]
Ad Dokumentation: bitte im source-folder in den (soeben neu erstellten) 'scraper' folder ein eigenes rst-file machen. Hab da grad ein dummy dafuer erstellt, bitte von Master pullen, dann seht ihr, wo ich mein'!

**Comment by fin** [comment]
Geschlossen weil implementiert.

@shellmayr ich habe keine Doku in docs/source/scraper gefunden. könntest du dir das nochmal ansehen, evtl einfach committen vergessen? (:

**Comment by shellmayr** [comment]
hey @fin, 

da wäre die, die ich committed hab, oder meinst du was anderes?
https://github.com/Forum-Informationsfreiheit/OffenesParlament/blob/master/offenesparlament/docs/source/scraper/inquiries.rst

**Comment by fin** [comment]
oh sorry, hab die wohl wegen der übersetzung verwechselt! danke (:
