### ISSUE TITLE
Error when creating an email alert based on search result

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#63]
When trying to set up an Email alert, I get the message: 
"Benachrichtigungen abonnieren
Ihr Abo für Periode XXV: amtsgeheimnis konnte nicht eingerichtet werden. Bitte versuchen Sie es erneut."

I searched for "amtsgeheimnis" on the front page, then tried to set up an alert for that serach

**Comment by benfreu** [comment]
@fin @lyrixderaven This is a general problem with the CSRF token.
The client code gets the code from the cookie "csrftoken". Is this cookie set by the server?

**Comment by fin** [comment]
cannot reproduce. what's wrong here?

**Comment by hutershvili** [comment]
I just tried again in all my browsers – Safari, Firefox, Chrome: no luck, always that error message

**Comment by fin** [comment]
ok, can reproduce now, will fix.

**Comment by fin** [comment]
this _should_ be fixed, can you retry?

**Comment by hutershvili** [comment]
yup, works fine now in various browsers! thanks!
