### ISSUE TITLE
Status of schriftliche Anfragen not updated

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#65]
The status of schriftliche Anfragen appears to always show "offen", even with old ones for which there is a response. Probably connected to the issue of the broken links, 
https://github.com/Forum-Informationsfreiheit/OffenesParlament/issues/64

to replicate the issue, go to http://offenesparlament.at/schlagworte/Wirtschaftspolitik/
=> you see that all Schriftliche Anfragen have the status "offen"

**Comment by benfreu** [comment]
IMO the scraper should fill out the status field of the law when it finds a response to an inquiry

**Comment by fin** [comment]
fixed. run
`python manage.py scrape crawl inquiries -a llp=25 -a ignore_timestamp=True`
to rerun scraper and update index
