### ISSUE TITLE
Formatting of debatten

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#66]
The debate pages of Bundesrat sessions and Nationalrat sessions need improved formatting:
– pictures of speakers have various sizes
– I guess text of spoken statements should be next to the picture and name of speaker, not below

For debates of the Bundesrat, you have a list of all speakers on top; that is not the case with debates of the Nationalrat. 

http://offenesparlament.at/debatten/XXV/NR/67
http://offenesparlament.at/debatten/XXV/BR/840

**Comment by benfreu** [comment]
The formatting issue should be old & cached CSS in your browser. Please hit command-shift-R or ctrl-shift-R or ctrl-R to reload the page and try again. if it persists, please re-open this issue.

The list of speakers is only displayed when there really were speakers. the NR/67 debate was just a "debate" of the president assigning a bunch of tasks to committees.
