### ISSUE TITLE
Search: Problem with changing Gesetzgebungsperiode

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#67]
There appears to be an issue with changing the Legislaturperiode in the search. 

=> I go to http://offenesparlament.at/debatten/XXV/ and try to search in a previous Gesetzgebungsperiode but there is no option to delete or change the current Gesetzgebungsperiode in the search

**Comment by benfreu** [comment]
This is linked to #61 and should work when #61 is resolved.
