### ISSUE TITLE
[CodeBounty] Petitionen & Bürgerinitiativen

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#7]
# Petitionen & Bürgerinitiativen

**Scraper**: € 600
**Frontend**: € 200

Petitionen werden von mindestens fünf ParlamentarierInnen eingebracht
Bürgerinitiativen werden von mindestens 500 BürgerInnen (handschriftlich Unterschrieben) eingebracht

Petitionen & BIs können über die Parlaments-Website “unterschrieben” werden, wenn sie einmal eingebracht wurden
### Scraper

Einstiegsseite: http://www.parlament.gv.at/PAKT/BB/
Beispielseite (BI): http://www.parlament.gv.at/PAKT/VHG/XXV/BI/BI_00083/index.shtml
Beispielseite (Pet): http://www.parlament.gv.at/PAKT/VHG/XXV/PET/PET_00032/index.shtml

Zu scrapen:
- Einbringer
- Parlamentarisches Verfahren
- Zustimmungserklärungen
### Frontend

Anzahl der Zustimmungen, welche Parteien dafür/dagegen, wenn abgeschlossen:
http://www.parlament.gv.at/PAKT/VHG/XXV/PET/PET_00032/index.shtml#tab-ParlamentarischesVerfahren

**Comment by Horrendus** [comment]
Ich würd gern den Scraper Teil dieser CodeBounty übernehmen.

Mein Fork: https://github.com/Horrendus/OffenesParlament

**Comment by hutershvili** [comment]
super!

**Comment by Horrendus** [comment]
Damit die Info auch hier steht (für evtl. Frontend Interessierte): Scraper fertig und wurde in master gemerged: e76d055a1414acdf30e8172e46fe177d9ac3c0e1

**Comment by fin** [comment]
Geschlossen. @Horrendus bist du mit der Dokumentation soweit zufrieden?
