### ISSUE TITLE
Search results: only shows results in "Gesetze", not from Debatten

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#72]
A search only appears to show results related to Gesetze, Anträge or Schriftliche Anfragen but it doesn't appear to include results from debates of the Nationalrat and Bundesrat.

For example, I searched for "hypo" and did not get any results
http://offenesparlament.at/suche/debatten?llps=XXV&q=hypo

**Comment by lyrixderaven** [comment]
Fixed in 6a74eeed556ae463917fa897d2c4658700d28ec9.

Needs a update_index call:

```
python manage.py update_index op_scraper.Debate -b 100
```

**Comment by fin** [comment]
(index rebuilt on live)
