### ISSUE TITLE
Send email on error/stacktrace from production

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#74]
The logging setup for production should be adapted so we/an email-adress of our choice/a mailing-list receives an email with the error and the link whenever a stacktrace happens. This would make debugging errors that occur in production much easier.

**Comment by fin** [comment]
the errors weren't logged, i decided to enable DEBUG temporarily.

**Comment by lyrixderaven** [comment]
cool, also an option. weird though that the errors weren't logged... clearly, we need to work on our logging setup a bit (probably both for production and for dev as well).

**Comment by fin** [comment]
i enabled sentry and logging, errors should therefore show up in /django/$DOMAIN/logs/gunicorn.log as well.
