### ISSUE TITLE
Show status of Anfrage on the profile of a Person

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#76]
It might improve usability if we could also show the status of an Anfrage on the profile of an Abgeordnete(r), in addition to Datum, Titel, Empfänger and Nummer. 

For example at
http://offenesparlament.at/personen/PAD_83119/Alm-Nikolaus-Mag-/

**Comment by themistress** [comment]
Good idea if easy to realise! In the same table, the columns "Empfänger" and "Nummer" could use more width.

**Comment by benfreu** [comment]
This is fairly easy to implement. Could be added as soon as #65 is resolved.
