### ISSUE TITLE
Broken links: Redebeiträge

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#77]
Links are also broken when you go to a profile of a Person and click on "Redebeitrag auf Parlament.gv.at"
http://offenesparlament.at/personen/PAD_36907/Dr-Johann-Georg-Schelling/

**Comment by benfreu** [comment]
@lyrixderaven is this a problem of partial scraping that will vanish when we have a complete scrape?
iirc we had a similar problem once

**Comment by lyrixderaven** [comment]
I don't think so. AFAICS the scraping is completed already; statements don't necessarily have a protocol_url (already); before the protocol has been transcribed, it won't show up and we won't find one. You need to check if protocol_url is not None and only then show the link in the template.

**Comment by fin** [comment]
also sometimes links are not prefixed by http://parlament.gv.at :/
