### ISSUE TITLE
[CodeBounty] Protokolle - Reden, Zwischenrufe   

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#8]
# Protokolle - Reden, Zwischenrufe

**Scraper**: 2200
**Frontend**: 1000
### Scraper

Einstiegsseite: http://www.parlament.gv.at/PAKT/STPROT/
Detailsseite (Beispiel): http://www.parlament.gv.at/PAKT/VHG/XXV/NRSITZ/NRSITZ_00072/fnameorig_447647.html

Zu bearbeiten:
- Scrapen des Inhaltsverzeichnisses (‘Verhandlungen’) der Protokolle auf RednerInnen (sowohl Abgeordnete als auch Mitglieder der Regierung!)
- Scrapen der einzelnen Reden
- Extrahieren von Links auf Personen; Ersetzen der Links auf die Personen-Detailseite auf parlament.gv.at durch Links auf die Personen-Detailseite auf OffenesParlament.at
- Crossreferencing: Anpassen des ‘Statement’ Models um den Volltext aufnehmen zu können, Verlinkung mit bereits existierenden Statement-Model oder Neu-Erstellen von Statement-Model und deren Link zu Personen-Model

**Achtung**: Aufgrund der Datenmenge, muss ein besonderes Augenmerk auf Performance gelegt werden; falls das Scrapen zu lange dauert, muss eine Lösung zum asychronen Triggern des Scrapens einzelner Protokoll entwickelt werden (um den Server nicht zu überlasten).

_Das Einbinden der gescrapeten Statements in ElasticSearch übernimmt das Team von OffenesParlament!_
### Frontend

_Tasks_:
- Entwicklung von Darstellungsform einer Detailseite pro Rede
- Einbetten von (Volltext) Reden/Wortmeldungen in Personen-Detailsseite

**Comment by mfit** [comment]
Möchte den scraper umsetzen, Fork ist hier: https://github.com/mfit/OffenesParlament

**Comment by lyrixderaven** [comment]
Pull Request was already merged (some changes in return-pull-request).

What doesn't work (yet?) is the statement-person-connection. AFAICS, the following statements won't work:

```
keys = set(data.keys()) &\
            set([v.name for v in DebateStatement._meta.get_fields()])
        for key in keys:
            setattr(debate_statement, key, data[key])
        debate_statement.save()
```

You're choosing to set all the relevant attributes of the model instance automatically, but that doesn't work in this case, because the foreign key for the person model is person_id, which doesn't show up in the key-list (try putting an import ipdb; ipdb.set_trace() statement after the 'save()' call and introspect the keys variable to confirm). Please address!

**Comment by lyrixderaven** [comment]
Furthermore, the 'detail_url' seems to be required (can't edit it in the admin-interface without filling it in), which is problematic, since it seems like not all Debates have detail_urls set. Is there a reason why it's mandatory?

**Comment by mfit** [comment]
Ok. Second one is due to switch to the RSS feed as source of debates, for which the detail_url is not yet extracted (besides that the field does not have to be mandatory).

Will attend to both soon

**Comment by mfit** [comment]
Empty person_id seemed actually due to a different name for the field in the data to be stored than in the actual model

**Comment by fin** [comment]
Are y'all happy and done with this?

**Comment by mfit** [comment]
Not quite, there are substantial improvements I'm still working on , at the moment https://github.com/mfit/OffenesParlament/tree/debinspect , will issue pull request soon .

**Comment by fin** [comment]
@mfit gibt's eine möglichkeit, die Zuordnung zu den Tagesordnungspunkten halbwegs hinzubiegen?

**Comment by mfit** [comment]
@fin ist da gemeint Redebeiträge zu Tagesordnungspunkt, oder die Tagesordnungspunkte zur Debatte

**Comment by fin** [comment]
Geschlossen, weil implementiert.

@mfit könntest du nochmal über doku drüberschaun? in docs/source habe ich zumindest nichts gefunden.

**Comment by mfit** [comment]
Ja, werde noch doku hinzugeben
