### ISSUE TITLE
Create frontend for Opinions (Stellungnahmen bei Begutachtungen)

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#83]
We have yet to develop a front-end for opinions (Stellungnahmen während Begutachtungen/vorparlamentarischen Verfahren), which are already scarped.

**Comment by fin** [comment]
we already link directly to the PDFs where they are listed, no?
as long as we don't actually ingest/OCR the PDFs there's nothing we can add to this, in my opinion.

example: http://offenesparlament.at/gesetze/XXV/395_d.B./ - PDF links right next to Parliament Site link

**Comment by hutershvili** [comment]
Sorry, you are right. I apparently had looked at the wrong laws...
