### ISSUE TITLE
[Text] Debates (Debatten)

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#85]
New suggested text for the debates page: http://offenesparlament.at/debatten/XXV/ 

**Debatten** 
Hier finden Sie eine Übersicht aller Sitzungen von Nationalrat und Bundesrat seit der letzten Nationalratswahl. 
Leider sind vorläufige stenographische Protokolle von Sitzungen der vergangenen Wochen derzeit nur über parlament.gv.at zugänglich.

**Comment by themistress** [comment]
Would’t start a sentence with "Leider" as it sounds very negative. What about:

Hier finden Sie eine Übersicht aller Sitzungen von Nationalrat und Bundesrat seit der letzten Nationalratswahl. Vorläufige stenographische Protokolle von Sitzungen der vergangenen Wochen derzeit nur über parlament.gv.at zugänglich.

**Comment by hutershvili** [comment]
you are totally right, let's do your version!
