### ISSUE TITLE
Link to Person in Anfragen & Beantwortungen leads to 500 Server Error

### ISSUE THREAD

**Issue by quicquid** [Forum-Informationsfreiheit/OffenesParlament#86]
If you navigate to http://offenesparlament.at/gesetze/XXV/AB_07549/ you find the answered by link to http://offenesparlament.at/personen/PAD_52687/Alois-St%C3%B6ger-dipl-m-/ which leads to a Server Error (500). Since the link is rendered as "Alois Stöger, diplômé", i tried to remove the "-dipl-m-" in the URL, but that also doesn't work.

**Comment by fin** [comment]
@benfreu has fixed this, but it hasn't been deployed yet (:
should be online in ~10min

**Comment by quicquid** [comment]
Thanks. By the way, http://offenesparlament.at/suche/personen?llps=XXV&q=St%C3%B6ger also doesn't give to a result, don't know if it is related.
