### ISSUE TITLE
[Text] Persons (Personen)

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#87]
New suggested Text for Personen, http://offenesparlament.at/personen/XXV/

**Personen**
Hier finden Sie eine Übersicht von Abgeordneten zum Nationalrat, Mitgliedern des Bundesrats und Regierungsmitgliedern mit Nationalratsmandat während der aktuellen Gesetzgebungsperiode. Um eine genauere Auswahl zu treffen, können Sie die Suche oben benutzen. 

Derzeit können wir nicht immer die aktuellste Fraktionszugehörigkeit eines/r Abgeordneten darstellen.

**Comment by themistress** [comment]
Same as with #85 – neutral wording would be better. (We have a lot of features, don’t hint people only to the negative in the intro)

**Comment by hutershvili** [comment]
thanks for the feedback, I edited the wording to reflect it.
