### ISSUE TITLE
Persons (Personen): Members of government who were not elected to Parliament are not listed

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#88]
We currently do not appear show member of government that were not elected to Parliament at http://offenesparlament.at/personen/XXV/. 

Example: http://offenesparlament.at/personen/PAD_83297/MMag-Dr-Sophie-Karmasin/

An eventual fix of this issue might avoid some confusion.

**Comment by lyrixderaven** [comment]
The issues is based on the problem that members of government are not getting a llp attached to their function when scraping, thus they don't show up in the searches. I'll investigate if we can actually add those llps while scraping.
