### ISSUE TITLE
[CodeBounty] Ausschüsse  

### ISSUE THREAD

**Issue by lyrixderaven** [Forum-Informationsfreiheit/OffenesParlament#9]
# Ausschüsse

**Scraper**: 400
**Frontend**: 400

Ausschuss-Liste plus Verbindung zwischen Ausschuss-Model und Parlamentarier-Model herstellen
### Scraper

_Einstiegsseite_: http://www.parlament.gv.at/PAKT/AUS/
_Detailseite_: http://www.parlament.gv.at/PAKT/VHG/XXV/A-AU/A-AU_00001_00361/index.shtml

**Tips**: 
- Der RSS-Link auf der Einstiegsseite rechts oben bezieht sich immer auf die aktuell gewählten Formulareinstellungen - praktisch zum reverse engineering der URLs.
- Tabs auf den Detailseiten sind rein im Frontend implementiert; für das Scrapen daher am Besten immer die HTML-Source betrachten!

**Zu Beachten**: 
- Ausschüsse können sowohl dem Bundesrat als auch dem Nationalrat zugehörig sein - bitte beides beachten.
- Unbedingt zu scrapen: Sitzungstermine, wo vorhanden
- ‘Meldungen der Parlamentskorrespondenz’ können derzeit noch ignoriert werden

_Beispielseite für Ausschussmitglieder_: http://www.parlament.gv.at/PAKT/VHG/XXV/A-AU/A-AU_00001_00361/MIT_00361.html
oder
http://www.parlament.gv.at/WWER/PAD_51564/#tab-Ausschuesse

Eher von der Parlamentarier-Seite ausgehen, Achtung: Posten können in der Vergangenheit liegen. Bitte diese dann trotzdem parsen (:. Generell wird es sich anbieten, für Ausschusszugehörigkeit ein eigenes Model zu erstellen (zb. Membership), da dann auch ein Start- und End-Datum der Zugehörigkeit pro Person/Ausschuss möglich ist.
### Frontend

**Tasks**:
- Grundlegende Ausschuss-Seite, inklusive Liste der Mitglieder
- Erweiterung der Parlamentarier-Seiten um die Liste der Ausschussmitgliedschaften
# Ausschuss-Details

**Scraper**: 500
**Frontend**: 100
### Scraper

Tasks: 
- Tagesordnungen
- Verhandlungsgegenstände 
- Liste der Veröffentlichungen

**Beispielseite Tagesordnungen** 
http://www.parlament.gv.at/PAKT/VHG/XXV/A-AU/A-AU_00001_00361/index.shtml#tab-Sitzungsueberblick
- 5. Sitzung hat TOPs. Diese Scrapen und mit den Verhandlungsgegenständen (Gesetzen, Petitionen) - falls schon gescraped - verbinden

**Beispielseite Verhandlungsgegenstände**
http://www.parlament.gv.at/PAKT/VHG/XXV/A-AU/A-AU_00001_00361/index.shtml#tab-Verhandlungsgegenstaende
- Scrapen und mit den Verhandlungsgegensätzen - falls schon gescraped - verbinden

**Beispielseite Veröffentlichungen**
http://www.parlament.gv.at/PAKT/VHG/XXV/A-AU/A-AU_00001_00361/index.shtml#tab-VeroeffentlichungenBerichte
### Frontend

Einfach auf Ausschuss-Seite die Listen für die drei Kategorien ausgeben

**Comment by Horrendus** [comment]
Da meine andere CodeBounty ja feature complete (und zumindest von mir getestet ist) und Spaß gemacht hat, würd ich gern auch die Ausschüsse machen falls sie noch offen sind (wieder nur Scraper)

**Comment by hutershvili** [comment]
Sehr gerne – an denen arbeitet noch niemand!

**Comment by hutershvili** [comment]
Sehr gerne – an denen arbeitet noch niemand!


2015-10-28 13:46 GMT+01:00 Stefan Derkits <notifications@github.com>:

**Comment by Horrendus** [comment]
:+1: Falls wer den Fortschritt verfolgen will, hier befindet sich mein Clone: https://github.com/Horrendus/OffenesParlament/tree/comittees

**Comment by sk7** [comment]
ich schau mir mal das frontend an

**Comment by fin** [comment]
@sk7 können wir noch womit rechnen?

**Comment by fin** [comment]
implemented by @benfreu
