### ISSUE TITLE
Manage Abos: reference to fin@fin.io

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#95]
When managing your email subscriptions, the page always refers to fin@fin.io

Replicate: http://offenesparlament.at/abos/mathias.huter@informationsfreiheit.at

"Benachrichtigungen für fin@fin.io
Ein Login-Link wurde soeben an 'mathias.huter@informationsfreiheit.at' gesendet (falls wir ein Abo unter dieser Adresse in unserer Datenbank gefunden haben)."

**Comment by fin** [comment]
this is probably because you're logged in as admin
@benfreu maybe the auth middleware overwrites the user variable? maybe pick another name?

**Comment by lyrixderaven** [comment]
Hm, seeing that I just could click the above link and that I got Mathias' email address it seems to work for me? It could be a caching issue in the browser... 

Besides that, I do think we need to put a captcha solution on that page. Misuse is totally obvious otherwise...

**Comment by fin** [comment]
ooh, rabbit hole!

additional issue: i don't think we should send emails based on GET requests

**Comment by benfreu** [comment]
true true true...

is everybody comfortable with using Google reCAPTCHA?

**Comment by themistress** [comment]
Fine for me!

**Comment by benfreu** [comment]
I've implemented a simple honeytrap thing for the email form.

Would we be able to spot abuse should it happen at some point?

**Comment by fin** [comment]
depends on your logging (:
