### ISSUE TITLE
Bundesrat Personen throw 500

### ISSUE THREAD

**Issue by fin** [Forum-Informationsfreiheit/OffenesParlament#96]
Since their Committees don't have LLPs

http://www.offenesparlament.at/personen/PAD_18446/Tiefnig-Ferdinand/
https://app.getsentry.com/share/issue/37323338362e313230313437363932/

**Comment by lyrixderaven** [comment]
I mentioned this to Ben quite a few months ago already at a meeting - we need to create URL patterns for those laws/comittees/etc. that simply don't have and never will have an LLP. It shouldn't be a bigger deal than just adding patterns to the urls.py file and linking to the same templates.

**Comment by benfreu** [comment]
This should be fixed now. I have to say Bundesrat parl_id are sometimes impossible to reconstruct from the algorithm we use to make them url-safe and the problem were committees here. Will address this in a separate issue
