### ISSUE TITLE
Petitions: Link on Frontpage?

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#99]
Petitions (Bürgerinitativen und Petitionen) looks great! A difficult to find (mostly over MPs profiles, if they have initiated a Petition), through Schlagworte you get to a different view of Petitionen and Bürgerinitiativen. I was wondering, would it make sense to have a small link to http://offenesparlament.at/petitionen/XXV/ on the frontpage?

**Comment by benfreu** [comment]
We decided to remove the petitions list as we weren't sure where it would fit in the site's structure and it isn't integrated into our search, so switching between LLPs is impossible ATM for petitions.

I'll remove the routing code for pages like this (same for #100 ) so they shouldn't be accessible anymore.
